name: Event demo 1
on:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
    branches:
        - main # main
        - 'dev-*' # dev-rc, dev-new
        - 'feat/**' # feat/new feat/new/rc
  workflow_dispatch:
  push:
    branches:
        - main # main
        - 'dev-*' # dev-rc, dev-new
        - 'feat/**' # feat/new feat/new/rc
    paths-ignore:
        - '.github/workflows/*'
jobs:
    demo:
      runs-on: ubuntu-latest
      steps:
        - name: Output event
          run: echo {{ toJSON(github.event) }}
        - name: Get code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Run linting
          run: npm run lint
        - name: Run test
          run: npm run test
        - name: Run build
          run: npm run build
        - name: Deploy project
          run: echo "Deploying..."
