name: Deployment app
on: push
jobs:
    # lint:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Run linting
        #   run: npm lint
    test:
    #   needs: lint
      runs-on: ubuntu-latest
      steps:
        - name: Run linting
          run: npm test
    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Run linting
          run: npm build
