name: Output information
on:
    issues:
      types: [opened, edited, milestoned]
jobs:
  info-issue:
    runs-on: ubuntu-latest
    steps:
        - name: Get issues info
          run: echo "${{ toJson(github.event.issue) }}"
